import { useState, useEffect } from 'react'
import axios from 'axios'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { Button } from '../components/ui/button'
import { Badge } from '../components/ui/badge'
import {
  Code,
  Download,
  Copy,
  CheckCircle,
  Loader2,
  Zap,
  FileJson,
  Bot
} from 'lucide-react'

export default function CodeFuserWorking() {
  const [agents, setAgents] = useState([])
  const [selectedAgent, setSelectedAgent] = useState(null)
  const [generatedCode, setGeneratedCode] = useState('')
  const [codeType, setCodeType] = useState('python')
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    loadAgents()
  }, [])

  const loadAgents = async () => {
    try {
      const response = await axios.get('http://localhost:8000/api/agents')
      setAgents(response.data || [])
    } catch (error) {
      console.error('Failed to load agents:', error)
    }
  }

  const generateCode = () => {
    if (!selectedAgent) return

    setIsGenerating(true)
    setTimeout(() => {
      let code = ''
      
      if (codeType === 'python') {
        code = `#!/usr/bin/env python3
"""
Agent Integration: ${selectedAgent.name}
Generated by GPTGram Code Fuser
"""

import requests
import json
import hmac
import hashlib
import uuid
from datetime import datetime

class ${selectedAgent.name.replace(/\s+/g, '')}Agent:
    def __init__(self):
        self.endpoint = "${selectedAgent.endpoint_url}"
        self.agent_id = "${selectedAgent.id}"
        self.hmac_secret = "${selectedAgent.hmac_secret || 's3cr3t'}"
        
    def execute(self, input_data):
        """Execute the agent with given input"""
        # Generate HMAC signature
        payload = json.dumps(input_data)
        signature = hmac.new(
            self.hmac_secret.encode(),
            payload.encode(),
            hashlib.sha256
        ).hexdigest()
        
        # Prepare headers
        headers = {
            'Content-Type': 'application/json',
            'X-GPTGRAM-Signature': f'sha256={signature}',
            'X-GPTGRAM-Idempotency': str(uuid.uuid4())
        }
        
        # Make request
        response = requests.post(
            f'http://localhost:8000/api/agents/{self.agent_id}/execute',
            headers=headers,
            json=input_data
        )
        
        if response.status_code == 200:
            return response.json()
        else:
            raise Exception(f'Agent execution failed: {response.status_code}')

# Usage example
if __name__ == '__main__':
    agent = ${selectedAgent.name.replace(/\s+/g, '')}Agent()
    
    # Example input
    input_data = {
        "text": "Your input text here"
    }
    
    try:
        result = agent.execute(input_data)
        print("Success:", json.dumps(result, indent=2))
    except Exception as e:
        print("Error:", str(e))
`
      } else if (codeType === 'javascript') {
        code = `// Agent Integration: ${selectedAgent.name}
// Generated by GPTGram Code Fuser

const axios = require('axios');
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');

class ${selectedAgent.name.replace(/\s+/g, '')}Agent {
    constructor() {
        this.endpoint = '${selectedAgent.endpoint_url}';
        this.agentId = '${selectedAgent.id}';
        this.hmacSecret = '${selectedAgent.hmac_secret || 's3cr3t'}';
    }
    
    async execute(inputData) {
        // Generate HMAC signature
        const payload = JSON.stringify(inputData);
        const signature = crypto
            .createHmac('sha256', this.hmacSecret)
            .update(payload)
            .digest('hex');
        
        // Prepare headers
        const headers = {
            'Content-Type': 'application/json',
            'X-GPTGRAM-Signature': \`sha256=\${signature}\`,
            'X-GPTGRAM-Idempotency': uuidv4()
        };
        
        try {
            const response = await axios.post(
                \`http://localhost:8000/api/agents/\${this.agentId}/execute\`,
                inputData,
                { headers }
            );
            return response.data;
        } catch (error) {
            throw new Error(\`Agent execution failed: \${error.message}\`);
        }
    }
}

// Usage example
async function main() {
    const agent = new ${selectedAgent.name.replace(/\s+/g, '')}Agent();
    
    const inputData = {
        text: 'Your input text here'
    };
    
    try {
        const result = await agent.execute(inputData);
        console.log('Success:', JSON.stringify(result, null, 2));
    } catch (error) {
        console.error('Error:', error.message);
    }
}

if (require.main === module) {
    main();
}

module.exports = ${selectedAgent.name.replace(/\s+/g, '')}Agent;
`
      } else if (codeType === 'curl') {
        const payload = JSON.stringify({ text: "Your input text" })
        const signature = 'YOUR_HMAC_SIGNATURE_HERE'
        
        code = `#!/bin/bash
# Agent: ${selectedAgent.name}
# Endpoint: ${selectedAgent.endpoint_url}

# Generate HMAC signature (requires openssl)
PAYLOAD='${payload}'
SECRET='${selectedAgent.hmac_secret || 's3cr3t'}'
SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | cut -d' ' -f2)

# Execute agent
curl -X POST http://localhost:8000/api/agents/${selectedAgent.id}/execute \\
  -H "Content-Type: application/json" \\
  -H "X-GPTGRAM-Signature: sha256=$SIGNATURE" \\
  -H "X-GPTGRAM-Idempotency: $(uuidgen)" \\
  -d "$PAYLOAD"
`
      }
      
      setGeneratedCode(code)
      setIsGenerating(false)
    }, 1000)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadCode = () => {
    const extension = codeType === 'python' ? 'py' : codeType === 'javascript' ? 'js' : 'sh'
    const filename = `${selectedAgent?.name.replace(/\s+/g, '_').toLowerCase()}_integration.${extension}`
    
    const blob = new Blob([generatedCode], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Code Fuser</h1>
        <p className="text-muted-foreground">
          Generate integration code for your agents
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Configuration */}
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Select Agent</CardTitle>
              <CardDescription>
                Choose an agent to generate integration code
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-sm font-medium">Available Agents ({agents.length})</label>
                <select
                  className="w-full mt-1 px-3 py-2 border rounded-lg"
                  onChange={(e) => {
                    const agent = agents.find(a => a.id === e.target.value)
                    setSelectedAgent(agent)
                  }}
                  value={selectedAgent?.id || ''}
                >
                  <option value="">Select an agent...</option>
                  {agents.map(agent => (
                    <option key={agent.id} value={agent.id}>
                      {agent.name} ({agent.price_cents}¢)
                    </option>
                  ))}
                </select>
              </div>

              {selectedAgent && (
                <div className="p-3 bg-muted rounded-lg">
                  <div className="flex items-start justify-between">
                    <div>
                      <h4 className="font-medium">{selectedAgent.name}</h4>
                      <p className="text-sm text-muted-foreground">
                        {selectedAgent.description || 'No description'}
                      </p>
                    </div>
                    <Badge>{selectedAgent.type}</Badge>
                  </div>
                  <div className="mt-2 text-xs">
                    <div>ID: {selectedAgent.id}</div>
                    <div>Price: {selectedAgent.price_cents}¢</div>
                    <div>Level: {selectedAgent.verification_level}</div>
                  </div>
                </div>
              )}

              <div>
                <label className="text-sm font-medium">Output Format</label>
                <div className="grid grid-cols-3 gap-2 mt-1">
                  <Button
                    size="sm"
                    variant={codeType === 'python' ? 'default' : 'outline'}
                    onClick={() => setCodeType('python')}
                  >
                    Python
                  </Button>
                  <Button
                    size="sm"
                    variant={codeType === 'javascript' ? 'default' : 'outline'}
                    onClick={() => setCodeType('javascript')}
                  >
                    JavaScript
                  </Button>
                  <Button
                    size="sm"
                    variant={codeType === 'curl' ? 'default' : 'outline'}
                    onClick={() => setCodeType('curl')}
                  >
                    cURL
                  </Button>
                </div>
              </div>

              <Button
                className="w-full"
                onClick={generateCode}
                disabled={!selectedAgent || isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Code className="h-4 w-4 mr-2" />
                    Generate Code
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* Info */}
          <Card>
            <CardHeader>
              <CardTitle>How It Works</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <div className="flex items-start space-x-2">
                <Badge className="mt-0.5">1</Badge>
                <div>Select an agent from your system</div>
              </div>
              <div className="flex items-start space-x-2">
                <Badge className="mt-0.5">2</Badge>
                <div>Choose your preferred programming language</div>
              </div>
              <div className="flex items-start space-x-2">
                <Badge className="mt-0.5">3</Badge>
                <div>Generate integration code with HMAC auth</div>
              </div>
              <div className="flex items-start space-x-2">
                <Badge className="mt-0.5">4</Badge>
                <div>Copy or download the code</div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Generated Code */}
        <div className="space-y-4">
          <Card className="h-[600px] flex flex-col">
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Generated Code</CardTitle>
              {generatedCode && (
                <div className="flex space-x-2">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={copyToClipboard}
                  >
                    {copied ? (
                      <>
                        <CheckCircle className="h-4 w-4 mr-1 text-green-600" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="h-4 w-4 mr-1" />
                        Copy
                      </>
                    )}
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={downloadCode}
                  >
                    <Download className="h-4 w-4 mr-1" />
                    Download
                  </Button>
                </div>
              )}
            </CardHeader>
            <CardContent className="flex-1 overflow-auto">
              {generatedCode ? (
                <pre className="text-xs font-mono bg-muted p-4 rounded-lg overflow-x-auto">
                  {generatedCode}
                </pre>
              ) : (
                <div className="h-full flex items-center justify-center text-muted-foreground">
                  <div className="text-center">
                    <FileJson className="h-12 w-12 mx-auto mb-4 opacity-50" />
                    <p>Select an agent and generate code</p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
